[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "icav2_tools"
version = "1.0.0"
description = "Useful layer for python lambdas that use ICAv2, smart-collection of the ICAv2 access token and other env vars"
license = "GPL-3.0-or-later"
authors = [
    "Alexis Lucattini"
]
homepage = "https://github.com/orcabus/platform-cdk-constructs"
repository = "https://github.com/orcabus/platform-cdk-constructs"

[tool.poetry.dependencies]
python = ">3.12,<3.15"
wrapica = "2.38.0.dev20250902211000"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"  # For testing only
# For typehinting only, not required at runtime
mypy-boto3-secretsmanager = ">=1.34.0, <2"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
priority = "supplemental"
