[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "orcabus_api_tools"
version = "1.0.0"
description = "A collection of secondary-level functions to use to interact with the OrcaBus"
license = "GPL-3.0-or-later"
authors = [
    "Alexis Lucattini"
]
homepage = "https://github.com/orcabus/platform-cdk-contsructs"
repository = "https://github.com/orcabus/platform-cdk-contsructs"

[tool.poetry.dependencies]
python = "^3.12, <3.13"
requests = "^2.31.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"  # For testing only
# For typehinting only, not required at runtime
mypy-boto3-ssm = "^1.34"
mypy-boto3-secretsmanager = "^1.34"
